### PR TITLE
 Add social share dialog with article-specific text

### PR DESCRIPTION
**Pull request by hsribei**
Originally I just changed the `title` field in the Twitter share button to have something contextual. (Facebook doesn't let you suggest the text for the user.)

But that was quite hidden so I went out on a limb and added this autosize textarea to allow the visitor to preview and edit the share text before clicking the button. 

Not sure if that's something you'd like to have so feel free to ask me to scrap it and just leave the button.

I *may* have gone a little too emojiful on the copywriting, so edit at will :)

### CODE REVIEW

**Comment by Swizec** [comment]
Ok so here's what I want you to do: You should separate this PR from the other stuff.

What if I want to merge this one before I merge the buy buttons? Building on top of one another like this takes that option away.

**Comment by Swizec** [comment]
Another thing I want you to add is making the social embeds (open graph and twitter card tags) customized for each lesson. That way when people share stuff it looks more correct.

**Comment by hsribei** [comment]
Yeah I was conflicted about separating on different branches as they would be editing the same file on adjacent lines, so would likely lead to merge conflicts, but you're right that not doing that makes it harder for you to pick which one to merge first. I'll rebase it on master. 👍 on og tags.

**Comment by hsribei** [comment]
Going to close this and open a new, cleaned up one.

**Pull request closed without merging**
